version: "3"

services:
  # Postgres DB
  local-db:
    container_name: local-db
    image: postgres:bullseye
    restart: always
    networks:
      - local-tier
    env_file:
      - ./apps/server/.env.development
    ports:
      - "5432:5432"

networks:
  local-tier:
    driver: bridge